=== rubencit04/LMSGI/Clase/WSLMSGI_Ruben/XML/Restriccionesexpresionesregulares/ciud.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="ciudad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z][a-zA-Z]{2,19}" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="codigo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Za-z]{2}-\d{2,5}" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="poblacion">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minExclusive value="100"></xs:minExclusive>
                            <xs:maxExclusive value="100000"></xs:maxExclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="alcalde">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-zA-Z]{0,10}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="apellidos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="[A-Za-z]+\s[A-Za-z]+" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minExclusive value="18"></xs:minExclusive>
                                        <xs:maxExclusive value="120"></xs:maxExclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:pattern value="[+]\d+[34]\d{9}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tarjeta_credito" type="xs:integer">
                            </xs:element>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[^@]+@[^\.]+\..+"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="funcionarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="funcionario" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z0-9]{1,10}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="50" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="apellidos">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="50" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="codigo_postal">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:pattern value="\d{5}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="fecha_nacimiento">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{2}/\d{2}/\d{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="contraseña">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z]\d{2,}[%$@!]"></xs:pattern>
                                                    <xs:minLength value="10"></xs:minLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="numero_cuenta">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="ES\d{4}\s\d{4}\s\d{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rubencit04/LMSGI/Clase/WSLMSGI_Ruben/XML/Restriccionesexpresionesregulares/ciudad.xml
<?xml version="1.0" encoding="UTF-8"?>
<ciudad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation= "ciud.xsd">
<nombre>Espana</nombre>
<codigo>LI-2342</codigo>
<poblacion>73613</poblacion>
<alcalde>
    <nombre>Alejandro</nombre>
    <apellidos>Lopez Gomez</apellidos>
    <edad>20</edad>
    <telefono>+34839123327</telefono>
    <tarjeta_credito>312314</tarjeta_credito>
    <email>pabloalboran@gmail.com</email>
</alcalde>
<funcionarios>
    <funcionario>
        <id>LE013418</id>
        <nombre>Pedro</nombre>
        <apellidos>Lopez Gonzalo</apellidos>
        <codigo_postal>01321</codigo_postal>
        <fecha_nacimiento>12/11/2002</fecha_nacimiento>
        <contraseña>M27780975%</contraseña>
        <numero_cuenta>ES2682 1837 6188</numero_cuenta>
    </funcionario>
</funcionarios>
</ciudad>
